### ISSUE TITLE
cannot run msi task

### ISSUE THREAD

**Issue by akasolace** [i-net-software/SetupBuilder#64]
Mistake is surely mine, but I cannot make msi task run without an error.
I am using latest stable graddle and latest SetupBuilder plugin (4.5.4d)

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':msi'.
> org.gradle.process.internal.DefaultExecAction: method <init>(Lorg/gradle/internal/file/PathToFileResolver;Ljava/util/concurrent/Executor;)V not found
```

I have a root and a sub module in my project. 

I tried to start from the example on the project page to make a msi out of my my root project.
I think my mistake comes from :
```
    from( 'build/libs' ) {
        include '*.jar'
    }
```
The directory I am refering to is the one in which the jar is compiled out of my source code. Is it what I am supposed to do?  I also tried to remove that block without success. 

Thank you in advance for your help

**Comment by Horcrux7** [comment]
This occur if the SetupBuilder version and Gradle version does not match. Because the internal Gradle API is very instabile that for different Gradle versions you need different plugin versions.

To prevent this you can use this script: https://github.com/i-net-software/SetupBuilder/blob/master/SetupBuilderVersion.gradle

**Comment by akasolace** [comment]
Thank you for the help.
But in the meantime, I decided to invoke msi directly from graddle and I managed to make it work.
